# Generated by Django 5.0.7 on 2024-08-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_inventory_category_alter_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('In stock', 'In stock'), ('On backorder', 'On backorder'), ('In transit', 'In transit'), ('Allocated', 'Allocated'), ('Shipped', 'Shipped')]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.category'),
        ),
    ]
