# Generated by Django 5.0.7 on 2024-08-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_status_alter_inventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(default='random@gmail.com', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_contact',
            field=models.CharField(max_length=20),
        ),
    ]
